### ISSUE TITLE
City Block Size

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/CityPlans#1]
How big is 1 City block? (E.g: # of mc blocks on Orion Boulevard between 1st Avenue and 2nd Avenue). Whatever the # is, it hasta be corresponding from 1st to whatever crosses 1st-15th on the other side in correlation to Orion Boulevard....
(Note, that the road hasta be evenly dotted, with the yellow lines having 2 concrete total before the white markings of an intersection, else the entire city is screwed.)

**Comment by LegoFan48737** [comment]
Answer: 116 blocks. 13,456 total area

**Comment by LegoFan48737** [comment]
Needs to be adjusted due to Nebulian Wayland-3 Measurement System

**Comment by KadTheHunter** [comment]
Closing this because, as proved in Orion Wayland 1 (Nebulian 4), making the entire city be a 40x40 grid is similar to saying there should be a standard cloud size. It could work, but it's extraordinarily retarded.
