### ISSUE TITLE
Shops....

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/CityPlans#2]
So, obv we're gonna have stuff like Fast Food, High end clothing stores, department stores, local downtown variety, etc, but its recently come to my attention that theres a Guns plugin, that essentially you can make guns with.... should we have a Guns shop? (in addition, I'd like everyones ideas for Shops, just comment them here please)
@Soap2953 @LegoFan48737 and hopefully you as well, Noah, Dare, DR, and anyone else who joins :)

**Comment by Soap2953** [comment]
yeah what could possibly go wrong?

**Comment by LegoFan48737** [comment]
> yeah what could possibly go wrong?

Everything, which is why we'll be placing gun shops down on the seedier areas (see [this](https://github.com/LegoFan48737/CityPlans/commit/eb35597204032311958e0d07befcf414a850320e))

**Comment by KadTheHunter** [comment]
*This aged well, lmao*

**Comment by KadTheHunter** [comment]
Locking conversation, will transfer to a new issue later.

**Comment by KadTheHunter** [comment]
Closed in #5
