### ISSUE TITLE
[Write Access]

### ISSUE THREAD

**Issue by ParadiseMCPE** [KadTheHunter/CityPlans#6]
So the servers always failed, would it be smart to just make a SMP for a while and in the background in a separate world work on other things that are more creative-based?

**Comment by ParadiseMCPE** [comment]
i fucked it up but hi kad

**Comment by KadTheHunter** [comment]
@ParadiseMCPE,

If you would like to request Write Access please open a new issue using the Write Access Form and answer the questions provided.
If you wish to discuss an Idea or Proposition, please open a new issue using the Idea Discussion Form.

Thank you for your interest in the CityBuild project,
- Kaddicus.
